export const images = {
  angularGradientFigma: "/images/angular-gradient-figma.png",
  supportersExtraGlow: "/images/extra-glow.png",
  logoDot: "/images/logo-dot-3daefd.png",
  dashboard: "/images/dashboard-2e99fc.png",
  lockFront: "/images/lock-front.png",
  featureSingle: "/images/feature-dashboard-full.png",
  collage1: "/images/collage-1-69c446.png",
  collage2: "/images/collage-2-62b44d.png",
  collage3: "/images/collage-3-6e740e.png",
  collage4: "/images/collage-4-2bf189.png",
  promptLibrary: "/images/prompt-library-36d63b.png",
  statUnion: "/images/stat-union.svg",
  ctaUnionCurve: "/images/curve/Header/103/Union.png",
  sparkleGroup2: "/images/sparkle-group-2.png",
  footerDivider: "/images/icons/social/footer-divider.svg",
  icons: {
    lock: "/images/icons/lock-laminated.png",
    wall: "/images/icons/wall.png",
    shieldCheck: "/images/icons/shield-check.png",
    fingerprint: "/images/icons/fingerprint.png",
    securityCamera: "/images/icons/security-camera.png",
    shieldWarning: "/images/icons/shield-warning.png",
    checkCircle: "/images/icons/check-circle.svg",
  },
} as const;
